// To parse this data:
//
//   import { Convert, PurchaseReceipt } from "./file";
//
//   const purchaseReceipt = Convert.toPurchaseReceipt(json);

import { PurchaseReceiptItem } from "./PurchaseReceiptItem.type";

export interface PurchaseReceipt {
	additional_discount_percentage?: number;
	address_display?: null;
	amended_from?: null;
	apply_discount_on?: string;
	apply_putaway_rule?: number;
	auto_repeat?: null;
	base_discount_amount?: number;
	base_grand_total?: number;
	base_in_words?: string;
	base_net_total?: number;
	base_rounded_total?: number;
	base_rounding_adjustment?: number;
	base_taxes_and_charges_added?: number;
	base_taxes_and_charges_deducted?: number;
	base_total_taxes_and_charges?: number;
	base_total?: number;
	billing_address_display?: null;
	billing_address?: null;
	buying_price_list?: string;
	company?: string;
	contact_display?: null;
	contact_email?: null;
	contact_mobile?: null;
	contact_person?: null;
	conversion_rate?: number;
	cost_center?: null;
	creation?: string;
	currency?: string;
	disable_rounded_total?: number;
	discount_amount?: number;
	docstatus?: number;
	doctype?: string;
	grand_total?: number;
	group_same_items?: number;
	idx?: number;
	ignore_pricing_rule?: number;
	in_words?: string;
	instructions?: null;
	inter_company_reference?: null;
	is_internal_supplier?: number;
	is_old_subcontracting_flow?: number;
	is_return?: number;
	is_subcontracted?: number;
	items?: PurchaseReceiptItem[];
	language?: string;
	letter_head?: null;
	lr_date?: null;
	lr_no?: string;
	modified_by?: string;
	modified?: string;
	name?: string;
	naming_series?: string;
	net_total?: number;
	other_charges_calculation?: null;
	owner?: string;
	per_billed?: number;
	per_returned?: number;
	plc_conversion_rate?: number;
	posting_date?: string;
	posting_time?: string;
	price_list_currency?: string;
	pricing_rules?: any[];
	project?: null;
	range?: null;
	rejected_warehouse?: null;
	remarks?: null;
	represents_company?: string;
	return_against?: null;
	rounded_total?: number;
	rounding_adjustment?: number;
	scan_barcode?: null;
	select_print_heading?: null;
	set_from_warehouse?: null;
	set_posting_time?: number;
	set_warehouse?: null;
	shipping_address_display?: null;
	shipping_address?: null;
	shipping_rule?: null;
	status?: 'Draft' | 'To Bill' | 'Completed' | 'Return Issued' | 'Cancelled' | 'Closed';
	supplied_items?: any[];
	supplier_address?: null;
	supplier_delivery_note?: null;
	supplier_name?: string;
	supplier_warehouse?: null;
	supplier?: string;
	tax_category?: string;
	taxes_and_charges_added?: number;
	taxes_and_charges_deducted?: number;
	taxes_and_charges?: null;
	taxes?: any[];
	tc_name?: null;
	terms?: null;
	title?: string;
	total_net_weight?: number;
	total_qty?: number;
	total_taxes_and_charges?: number;
	total_weight?: number;
	total_weight_difference_with_truck_weight?: number;
	truck_weight?: number;
	empty_truck_weight?: number;
	total?: number;
	transporter_name?: null;
	workflow_state?: string;
}
